- name: Create / Check backup directory
  file:
    path: "{{config_path}}"
    state: directory
    recurse: yes

- name: Get CPU Information
  connection: network_cli
  dellemc.enterprise_sonic.sonic_command:
    commands:
      - show system cpu
  register: cpu_info

- name: Format CPU Information
  set_fact:
    formatted_cpu_info: "{{ cpu_info.stdout | join('\n') | replace(\"['\", '') }}"

- name: Copy CPU Output
  copy:
    content: |
      {{ formatted_cpu_info }}
    dest: "{{config_path}}/{{inventory_hostname}}.cpu.txt"
