- name: Configure Dell SonicOS Switch
  hosts: inventory
  gather_facts: False
  connection: httpapi
  collections:
    - dellemc.enterprise_sonic

  tasks:
    - name: Remote Execute
      include_role:
        name: remote_execution
