- name: Configure Dell SonicOS Switch
  hosts: inventory
  gather_facts: False
  connection: httpapi
  collections:
    - dellemc.enterprise_sonic

  tasks:
    - name: Show Status
      include_role:
        name: show_status
